### ISSUE TITLE
您好，问一下，我们使用cdn引入的方式，怎么用这种方式使用这个插件呢？

### ISSUE THREAD

**Issue by xxi-arch** [ff755/vue-kindedtior-demo#3]

**Comment by ff755** [comment]
笨方法 照着vue文件 用js写一遍

**Comment by ff755** [comment]
demo下载地址
http://ft001.qiniudn.com/vue-kindeditor-single.zip

![image](https://cloud.githubusercontent.com/assets/24597602/26287252/551bc728-3eaa-11e7-8803-7bcf5ca2dd19.png)

**Comment by xxi-arch** [comment]
你好，我使用了你的demo，为什么没有办法赋值以及获取呢  我整理在http://runjs.cn/code/erqrvohc 上

**Comment by xxi-arch** [comment]
能否留个联系方式呢 ？

**Comment by ff755** [comment]
@544751779 不好意思 那个语法有问题  

改好了 这个是演示 全屏查看， 你可以把文件重新下载一下 本地试试
[http://runjs.cn/detail/8u7b5fl1](http://runjs.cn/detail/8u7b5fl1)
