### ISSUE TITLE
貌似用了keep-alive就会有问题，切换路由的时候编辑器就没办法focus了，要手动刷新浏览器才可以

### ISSUE THREAD

**Issue by doublemin** [ff755/vue-kindedtior-demo#5]

**Comment by ff755** [comment]
vue keep-alive 会缓存组件在内存中 来回切换不会重新渲染 用keep-alive的钩子函数看可以实现你要的功能吗

**Comment by doublemin** [comment]
组件和数据都还是在的，就是编辑框不显示之前填写的内容了，也无法聚焦填写新的内容。但是在activate和deactivated函数里还是能打印出原来的值。请问具体要怎么做呢？

**Comment by ff755** [comment]
deactivated函数 中 destroy 销毁，切换回去可以聚焦，但要显示之前编辑的内容只有把数据扔 vuex ，activated函数 里设置初始化内容。

使用 keep-alive 后切换回去 kindedtior html 结构发生变化了，所以无法聚焦，其实工具条上的内容全都不能使用了。console 会提示出错。

建议还是用 exclude 把相应组件忽略掉，每次重新渲染。目前没找到其它方法。
