### ISSUE TITLE
你好，请问插入图片弹出框的大小怎么改，我在kindeditor-all.js文件和plugins/image/images.js文件下改都不生效？

### ISSUE THREAD

**Issue by doublemin** [ff755/vue-kindedtior-demo#7]
你好，请问插入图片弹出框的大小怎么改，我在kindeditor-all.js文件和plugins/image/images.js文件下改都不生效？

**Comment by ff755** [comment]
看下main.js里面导入的具体文件
`
import 'kindeditor/kindeditor-all.js'   
`
在node_modules目录下找到kindeditor-all.js
7150行
`
var dialogWidth = showLocal || allowFileManager ? 450: 400,
dialogHeight = showLocal && showRemote ? 300 : 250;
`
具体数字自己填写
