### ISSUE TITLE
安装之后，运行就报错

### ISSUE THREAD

**Issue by cfhy** [ff755/vue-kindedtior-demo#8]
![image](https://user-images.githubusercontent.com/7599756/33814815-db72d4d0-de67-11e7-8f5a-455f127e5428.png)

**Comment by cfhy** [comment]
前面几位也遇到这个问题，没看到解决方法呀。

**Comment by ff755** [comment]
@cfhy 
本地用 vue-cli 新建项目没有报错
把项目 .babelrc 文件贴出来看看。

.babelir 配置文件里有 `stage-2`配置, pageage.json  dev 依赖需要    "babel-preset-stage-2"

错误提示找不到 `stage-2`

**Comment by cfhy** [comment]
![2017-12-18_101419](https://user-images.githubusercontent.com/7599756/34087291-0f865c4a-e3dd-11e7-93a6-97b4259a8f64.png)

**Comment by ff755** [comment]
@cfhy 改成stage-2试试 记得更新包

**Comment by cfhy** [comment]
我改成stage-2还是不行。然后按照示例重新创建了个新的项目没出现问题。
我把源码给你，你有空帮我瞧瞧吧，麻烦你了。我只是在iview-admin-dev中安装了vue-kindeditor，在main.js中按照示例拷贝了代码，其他的什么都没改动。
[iview-admin-dev.zip](https://github.com/ff755/vue-kindedtior-demo/files/1566818/iview-admin-dev.zip)

**Comment by ff755** [comment]
@cfhy 

 
https://github.com/ff755/vue-kindedtior-demo/blob/iview-admin-dev/iview-admin-dev%20-%20%E5%89%AF%E6%9C%AC.7z

去 iview-admin-dev 分支下载，可以正常显示。

**Comment by cfhy** [comment]
非常感谢
